config/routes.rb
Sp142ndm::Application.routes.draw do

  resources :alerts

  resources :transactions
  resources :exchanges
  resources :organizations
  resources :holdings

  ActiveAdmin.routes(self)
  get "home/index"
  root to: "home#index"
  devise_for :users

  get 'home/ticker' => 'home#ticker'
  get 'home/balance' => 'home#balance'

  get 'home/history' => 'home#history'

end

app/models/alert.rb
class Alert < ActiveRecord::Base
  attr_protected nil
  belongs_to :user
end

app/controllers/alerts_controller.rb
class AlertsController < InheritedResources::Base
  # POST /alerts
  # POST /alerts.json
  def create
     #@exchanges = Exchanges.all	
     @alerts = Alert.all
     @alert = Alert.new(params[:alert])
    # @alert.username = current_user.username
	@alert.user = current_user
     respond_to do |format|     
     if @alert.save
     # Tell the UserMailer to send a welcome email after save
     AlertMailer.alert_email(@alert, current_user).deliver
	

        #flash[:success] = "Alert added successfully!"
        #redirect_to_root_path

     	#redirect_to_root_path
	#format.html { redirect_to '/alerts' }
  	format.html { redirect_to('/alerts', notice: 'Alert was successfully created.') }
        #format.json { render json: @alert, status: :created, location: @alert }
      else
        format.html { render action: 'new' }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/_form.html.erb
<%= form_for(@alert) do |f| %>
  <% if @alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
      <% @alert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-xs-1"></div>
    <div class="col-xs-10">
      <div class="panel panel-primary">
        <div class="panel-heading">New Alert</div>
	<table class="table table-hover">
  <thead>
    <tr>
      <th>Price Difference</th>
      <th>Exchange 1</th>
      <th>Exchange 2</th>
      <th>Frequency</th>
      <th>Automatic</th>
      <th>Quantity</th>
	
 </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= f.text_field :price_difference, class: "form-control", :placeholder => "$" %></td>
	      <td><%= f.select :exchange1, options_for_select(Exchange.all.map{|exchange| ["#{exchange.name}", exchange.name] }),{}, {:class => "form-control"} %></td>
	      <td><%= f.select :exchange2, options_for_select(Exchange.all.map{|exchange| ["#{exchange.name}", exchange.name] }),{}, {:class => "form-control"} %></td>
	      <td><%= f.text_field :frequency, class: "form-control"%></td>
        <td><%= f.check_box :automatic, class: "checkbox" %></td>
        <td><%= f.text_field :quantity, class: "form-control" %></td>
        <td><%= f.submit 'Create Alert', :class => 'btn btn-success', :style=>"color: white;width:100%" %></td>

      </tr>
      <tr> </tr>   


  </tbody>
</table>	
  </div>
</div>
</div>
<% end %>

app/views/alerts/edit.html.erb
<script>
navtrans = document.getElementById("navtrans");
      navtran = document.getElementById("navtran");
      navhold = document.getElementById("navhold");
      navalert = document.getElementById("navalert");
      navdash.className = ""
      navtrans.className = ""
      navtran.className = ""
      navhold.className = ""
      navalert.className = "active"
</script>
<h1></h1>

<%= render 'form' %>
<div class="col-md-3"></div>
  <button type="button" class="btn btn-default">
<!--%= link_to 'Show', @alert %-->
<%= link_to 'Back', alerts_path %>
  </button>

app/views/alerts/index.html.erb
<script>
navtrans = document.getElementById("navtrans");
      navtran = document.getElementById("navtran");
      navhold = document.getElementById("navhold");
      navalert = document.getElementById("navalert");
      navdash.className = ""
      navtrans.className = ""
      navtran.className = ""
      navhold.className = ""
      navalert.className = "active"
</script>
<div class="col-md-2"></div>
  <div class="col-md-8">
    <div class="panel panel-primary" style="width: 700px;">
  <!-- Default panel contents -->

                  <div class="panel-heading">Alerts</div>
<!--h1>Alerts</h1-->

<table class="table">
  <thead>
    <tr>
      <th>Price Difference</th>
      <th>Exchange 1</th>
      <th>Exchange 2</th>
      <th>Frequency</th>
      <th>Automatic</th>
      <th>Quantity</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @alerts.where(:user => current_user).each do |alert| %>
      <tr>
        <td>$<%= alert.price_difference %></td>
	<td><%= alert.exchange1%></td>
	<td><%= alert.exchange2%></td>
	<td><%= alert.frequency%></td>
  <td><%= alert.automatic%></td>
  <td><%= alert.quantity%></td>
        

        <td><%= link_to 'Edit', edit_alert_path(alert) %></td>
        <td><%= link_to 'Destroy', alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



</div>
<button type="button" class="btn btn-default">
<%= link_to 'New Alert', new_alert_path %>
</button>

</div>

app/views/alerts/new.html.erb
<script>
navtrans = document.getElementById("navtrans");
      navtran = document.getElementById("navtran");
      navhold = document.getElementById("navhold");
      navalert = document.getElementById("navalert");
      navdash.className = ""
      navtrans.className = ""
      navtran.className = ""
      navhold.className = ""
      navalert.className = "active"
</script>
<h1></h1>

<%= render 'form' %>

app/views/alerts/show.html.erb
<script>
navtrans = document.getElementById("navtrans");
      navtran = document.getElementById("navtran");
      navhold = document.getElementById("navhold");
      navalert = document.getElementById("navalert");
      navdash.className = ""
      navtrans.className = ""
      navtran.className = ""
      navhold.className = ""
      navalert.className = "active"
</script>
<p id="notice"><%= notice %></p>


<table class="table">

<thead>
    <tr>
      <th>Price Difference</th>
      <!--th>User</th-->
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>$<%= @alert.price_difference %></td>
        <!--td><%= @alert.user.username %></td-->
        <td><%= link_to 'Edit', edit_alert_path(@alert) %></td>
        <td><%= link_to 'Destroy', @alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  </tbody>
</table>

<%= link_to 'Back', alerts_path %>