svcs/config/routes.rb
Svcs::Application.routes.draw do
 

  get 'bitstamp_svcs/balance' => 'bitstamp_svcs#bal'
  get 'bitstamp_svcs/buy' => 'bitstamp_svcs#buy'
  get 'bitstamp_svcs/sell' => 'bitstamp_svcs#sell'
  get 'coinbase_svcs/balance' => 'coinbase_svcs#bal'
  get 'coinbase_svcs/buy' => 'coinbase_svcs#buy'
  get 'coinbase_svcs/sell' => 'coinbase_svcs#sell'

end

svcs/app/models/balances.rb
class Balances < ActiveRecord::Base
end

svcs/app/models/bitstamp_svc.rb
class BitstampSvc < ActiveRecord::Base
end

svcs/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

svcs/app/controllers/bitstamp_svcs_controller.rb
require 'rest-client'
require 'json'
class BitstampSvcsController < ApplicationController

  def bal
      if(params[:key] != nil && params[:signature] != nil && params[:nonce] != nil)
      response = "{\"usd_balance\":\"100000\",\"btc_balance\":\""+Balances.where(:name => "Bitstamp").first.balance.to_s+"\",\"usd_reserved\":\"30000\",\"btc_reserved\":\"60\",\"usd_available\":\"100000\",\"btc_available\":\"200\",\"fee\":\"20\"}"
      render :json => response
      end
  end
  def buy
  	if(params[:key] != nil && params[:signature] != nil && params[:nonce] != nil)
      response = "{\"id\":\""+SecureRandom.uuid.to_s+"\",\"datetime\":\""+Time.now.to_s+"\",\"type\":\"0\",\"price\":\""+(params[:price].to_f*params[:amount].to_f).to_s+"\",\"amount\":\""+params[:amount].to_s+"\"}"
      balB = Balances.where(:name => "Bitstamp").first
      balB.balance = balB.balance.to_f + params[:amount].to_f
      balB.save
      render :json => response
      end
  end 
  def sell
  	if(params[:key] != nil && params[:signature] != nil && params[:nonce] != nil)
      response = "{\"id\":\""+SecureRandom.uuid.to_s+"\",\"datetime\":\""+Time.now.to_s+"\",\"type\":\"1\",\"price\":\""+(params[:price].to_f*params[:amount].to_f).to_s+"\",\"amount\":\""+params[:amount].to_s+"\"}"
      balB = Balances.where(:name => "Bitstamp").first
      balB.balance = balB.balance.to_f - params[:amount].to_f
      balB.save
      render :json => response
      end
  end 

end

svcs/app/controllers/coinbase_svcs_controller.rb
require 'rest-client'
require 'json'
require 'coinbase'

class CoinbaseSvcsController < ApplicationController

  def bal
      if(params[:key] != nil && params[:signature] != nil)
      #response = "{\"usd_balance\":\"100000\",\"btc_balance\":\""+Balances.where(:name => "Coinbase").first.balance.to_s+"\",\"usd_reserved\":\"30000\",\"btc_reserved\":\"60\",\"usd_available\":\"100000\",\"btc_available\":\"200\",\"fee\":\"20\"}"
      
      response = "{
  \"amount\": \""+Balances.where(:name => "Coinbase").first.balance.to_s+"\",
  \"currency\": \"BTC\"
}"

      render :json => response
      end
  end
  def buy
  	@coinbase = Coinbase::Client.new('9MB2hsDaSXvbevZ4', 'Yakw1TObmQrL2k4OMGcCVZqpdNLsPO2S')
  	if(params[:key] != nil && params[:signature] != nil)
      #response = "{\"id\":\""+SecureRandom.uuid.to_s+"\",\"datetime\":\""+Time.now.to_s+"\",\"type\":\"0\",\"price\":\""+(params[:price].to_f*params[:amount].to_f).to_s+"\",\"amount\":\""+params[:amount].to_s+"\"}"
      subamt = (@coinbase.buy_price(1)*(params[:qty].to_f))
      fee = 0.34
      response = "{
  					\"success\": true,
  					\"transfer\": {
    				\"type\": \"Buy\",
    				\"code\": \""+SecureRandom.uuid.to_s+"\",
    				\"created_at\": \""+Time.now.to_s+"\",
    				\"fees\": {
      					\"coinbase\": {
        					\"cents\": 14,
        					\"currency_iso\": \"USD\"
      					},
      					\"bank\": {
							\"cents\": 15,
							\"currency_iso\": \"USD\"
						}
    				},
				    \"status\": \"created\",
				    \"payout_date\": \""+SecureRandom.uuid.to_s+"\",
				    \"btc\": {
				      \"amount\": \""+params[:qty]+"\",
				      \"currency\": \"BTC\"
				    },
				    \"subtotal\": {
				      \"amount\": \""+subamt.to_s+"\",
				      \"currency\": \"USD\"
				    },
				    \"total\": {
				      \"amount\": \""+(subamt).to_s+"\",
				      \"currency\": \"USD\"
				    }
  }
}"

      balB = Balances.where(:name => "Coinbase").first
      varBal = balB.balance
      balB.balance = varBal + params[:qty].to_f
      balB.save
      render :json => response
      end
  end 
  def sell
  	@coinbase = Coinbase::Client.new('9MB2hsDaSXvbevZ4', 'Yakw1TObmQrL2k4OMGcCVZqpdNLsPO2S')
  	if(params[:key] != nil && params[:signature] != nil)
      #response = "{\"id\":\""+SecureRandom.uuid.to_s+"\",\"datetime\":\""+Time.now.to_s+"\",\"type\":\"0\",\"price\":\""+(params[:price].to_f*params[:amount].to_f).to_s+"\",\"amount\":\""+params[:amount].to_s+"\"}"
      subamt = (@coinbase.sell_price(1)*(params[:qty].to_f))
      fee = 0.34
      response = "{
  					\"success\": true,
  					\"transfer\": {
    				\"type\": \"Sell\",
    				\"code\": \""+SecureRandom.uuid.to_s+"\",
    				\"created_at\": \""+Time.now.to_s+"\",
    				\"fees\": {
      					\"coinbase\": {
        					\"cents\": 14,
        					\"currency_iso\": \"USD\"
      					},
      					\"bank\": {
							\"cents\": 15,
							\"currency_iso\": \"USD\"
						}
    				},
				    \"status\": \"created\",
				    \"payout_date\": \""+SecureRandom.uuid.to_s+"\",
				    \"btc\": {
				      \"amount\": \""+params[:qty]+"\",
				      \"currency\": \"BTC\"
				    },
				    \"subtotal\": {
				      \"amount\": \""+subamt.to_s+"\",
				      \"currency\": \"USD\"
				    },
				    \"total\": {
				      \"amount\": \""+(subamt).to_s+"\",
				      \"currency\": \"USD\"
				    }
  }
}"

      balB = Balances.where(:name => "Coinbase").first
      print balB.balance
      print "\n"
      print params[:qty]
      balB.balance = balB.balance.to_f - params[:qty].to_f
      balB.save
      render :json => response
      end
  end 

end

svcs/app/helpers/application_helper.rb
module ApplicationHelper
end

svcs/app/helpers/bitstamp_svcs_helper.rb
module BitstampSvcsHelper
end

svcs/app/helpers/coinbase_svcs_helper.rb
module CoinbaseSvcsHelper
end

svcs/app/views/bitstamp_svcs/_form.html.erb
<%= form_for(@bitstamp_svc) do |f| %>
  <% if @bitstamp_svc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bitstamp_svc.errors.count, "error") %> prohibited this bitstamp_svc from being saved:</h2>

      <ul>
      <% @bitstamp_svc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

svcs/app/views/bitstamp_svcs/edit.html.erb
<h1>Editing bitstamp_svc</h1>

<%= render 'form' %>

<%= link_to 'Show', @bitstamp_svc %> |
<%= link_to 'Back', bitstamp_svcs_path %>

svcs/app/views/bitstamp_svcs/index.html.erb
<h1>Listing bitstamp_svcs</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bitstamp_svcs.each do |bitstamp_svc| %>
      <tr>
        <td><%= link_to 'Show', bitstamp_svc %></td>
        <td><%= link_to 'Edit', edit_bitstamp_svc_path(bitstamp_svc) %></td>
        <td><%= link_to 'Destroy', bitstamp_svc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bitstamp svc', new_bitstamp_svc_path %>

svcs/app/views/bitstamp_svcs/new.html.erb
<h1>New bitstamp_svc</h1>

<%= render 'form' %>

<%= link_to 'Back', bitstamp_svcs_path %>

svcs/app/views/bitstamp_svcs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bitstamp_svc_path(@bitstamp_svc) %> |
<%= link_to 'Back', bitstamp_svcs_path %>

svcs/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Svcs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>