config/routes.rb
Sp142ndm::Application.routes.draw do

  resources :alerts

  resources :transactions
  resources :exchanges
  resources :organizations
  resources :holdings

  ActiveAdmin.routes(self)
  get "home/index"
  root to: "home#index"
  devise_for :users

  get 'home/ticker' => 'home#ticker'
  get 'home/balance' => 'home#balance'

  get 'home/history' => 'home#history'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
	attr_protected nil
	has_many :users
	has_and_belongs_to_many :exchanges
	def display_name
    	organization_name
  	end
  validates_presence_of :organization_name
end

app/controllers/organizations_controller.rb
class OrganizationsController < InheritedResources::Base
  before_filter :configure_permitted_parameters, if: :organizations_controller?
  def new
     @organization = Organization.new(org_params)
     #@organization.save
     #redirect_to @organization
       if @organization.save
        flash[:success] = "Organization added successfully!"
        redirect_to_root_path
       else
        render :new
end
  end
   
   private
   def org_params
    #params.require(:organization).permit(:organization_name, :user_name)
    params.require(:organization).permit(:organization_name)
   end
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organization_name %><br>
    <%= f.text_field :organization_name %>
  </div>
  <!--div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organization name:</strong>
  <%= @organization.organization_name %>
</p>

<p>
  <strong>User name:</strong>
  <%= @organization.user_name %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>